### ISSUE TITLE
Замечания по методу reduce

### ISSUE THREAD

**Issue by frontgirl** [pavelneznanov/netology-js#1]
https://github.com/pavelneznanov/netology-js/blob/be4e89c21da0642dd0aeb9a255c0ca23636738cd/game.js#L89

- переменная acc в данном случае - не аккумулятор, а "текущий максимум" длины строки, поэтому предлагаю поменять название на currentMax
- поиск наибольшего из 2х значений можно сделать проще с помощью Math.max()

**Comment by frontgirl** [comment]
я имела в виду такой код:
```
this.width = this.grid.reduce(function(currentMax, row){
      return Math.max(currentMax, row.length);
    }, 0);
```
Но если есть сложности с методом reduce (не самый понятный метод, соглашусь), можно оставить ваш вариант.

**Comment by pavelneznanov** [comment]
Я бы предложил оставить текущий вариант, т.к. сроки на приемку ограничены и скорее всего не успею разобраться самостоятельно
