### ISSUE TITLE
Логика проверки на lava и wall, которая находится ниже, должна быть вынесена в метод isIntersect

### ISSUE THREAD

**Issue by frontgirl** [pavelneznanov/netology-js#2]
https://github.com/pavelneznanov/netology-js/blob/be4e89c21da0642dd0aeb9a255c0ca23636738cd/game.js#L143

Внутри циклов должна быть проверка на наличие препятствия, и если isIntersect вернуло не undefined - то возвращать результат этой функции (а isIntersect, в свою очередь, возвращает undefined либо одно из препятствий в виде строки).

**Comment by pavelneznanov** [comment]
Сейчас не очень понимаю зачем это нужно и что это должно дать в результате.

Код должен быть такого вида?
```
        let actorItem = actor.isIntersect(currentCell);
        if (actorItem === 'undefined') {
          return actorItem;
        } else {
          if (column === 'wall') {
            obstacleWall = true;
          }
          if (column === 'lava') {
            obstacleLava = true;
          }
        }
```

**Comment by frontgirl** [comment]
isIntersect проверяет столкновение с движущимся объектом (нужно в методе actorAt), а здесь мы ищем только столкновение с неподвижными препятствиями.
Я не поняла, зачем хранить отдельно переменную obstacleWall и obstacleLava.
Возвращать нужно препятствие (если найдено), а не объект, поэтому название переменной не верное.
```
                if(pos.y + size.y > this.height) {
			return 'lava';
		}
		if(pos.x < 0 || pos.x + size.x > this.width || pos.y < 0) {
			return 'wall';
		}
```
а внутри цикла:
```
let obstacle = currentCell;
if (obstacle !== undefined){
    return obstacle;
}
```
в ячейке уже находится имя препятствия(если есть), достаточно возвращать это имя, получается, дополнительные переменные не нужны.

**Comment by frontgirl** [comment]
Увидела, что вы сделали точно так же.
